SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

ASTEROID_MIN_RADIUS = 20
ASTEROID_MID_RADIUS = ASTEROID_MIN_RADIUS * 2
ASTEROID_KINDS = 3
ASTEROID_SPAWN_RATE = 0.8  # seconds
ASTEROID_MAX_RADIUS = ASTEROID_MIN_RADIUS * ASTEROID_KINDS

PLAYER_RADIUS = 20
PLAYER_TURN_SPEED = 300
PLAYER_SPEED = 200

PLAYER_SHOOT_SPEED = 500
PLAYER_SHOOT_COOLDOWN = 0.3

SHOT_RADIUS = 5

SCORE_MAX_ASTEROID = 5
SCORE_MID_ASTEROID = 10
SCORE_MIN_ASTEROID = 20

ASTEROID_SPEED_MULTIPLIER_INCREMENT = 0.25